linux.py: handle systemd version without patch info
The get_systemd_version function introduced in

    55d35d5 linux: add get_systemd_version()

correctly handles

    systemd 244 (244.3+)
    +PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK -SYSVINIT...

but not

    systemd 234
    +PAM -AUDIT -SELINUX +IMA -APPARMOR -SMACK +SYSVINIT....

and the call ends with following exception:

    ValueError: Systemd version output changed

Fix it by ignoring anything that comes afer the version.

Signed-off-by: Adam Trhon <adam.trhon@tbs-biometrics.com>