linux: fix parsing of old systemd 'type' right after boot
With old systemd (before 240), just after boot, the
get_systemd_status_raw function fails with the following exception:

ValueError: invalid literal for int() with base 10: '2 "star'

Calling `print(path_and_id)` before parsing prints the following:

    /org/freedesktop/systemd1/unit/syslog_2eservice" 0 "
    /org/freedesktop/systemd1/unit/alsa_2drestore_2eservice" 0 "
    /org/freedesktop/systemd1/unit/dev_2dram0_2edevice" 0 "
    /org/freedesktop/systemd1/unit/multi_2duser_2etarget" 2 "start

The last line causes the error which is fixed by this patch.

Signed-off-by: Adam Trhon <adam.trhon@tbs-biometrics.com>